name: create-listing
on: 
  workflow_dispatch:
    inputs:
      item_number:
        required: true
      category:
        required: true
        type: choice
        options:
          - 'seedlings'
          - 'clones'
          - 'mutated'
          - 'other'
      description:
        required: true
        default: 'Description coming soon.'
      price:
        required: true
        default: 0
      is_sold:
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install XMLstarlet
        run: |
          sudo apt-get update
          sudo apt-get install xmlstarlet -y

      - name: Update XML listing
        run: |
          xmlstarlet ed -s "/listings" -t "newListing" -v "" \
          -s "/listings/newListing" -t -n "itemNumber" -v "${{ github.event.inputs.item_number }}" \
          -s "/listings/newListing" -t -n "category" -v "${{ github.event.inputs.category }}" \
          -s "/listings/newListing" -t -n "description" -v "${{ github.event.inputs.description }}" \
          -s "/listings/newListing" -t -n "price" -v "${{ github.event.inputs.price }}" \
          -s "/listings/newListing" -t -n "isSold" -v "${{ github.event.inputs.is_sold }}" \
          static/xml/listings.xml

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add static/xml/listings.xml
          git commit -m "Add new listing: ${{ github.event.inputs.item_number }}"
          git push